name: Rust Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Go to Rust Folder
      run: cd goals_backend
    - name: Run Check
      run: cargo check
    - name: Run Build
      run: cargo build --verbose
